# Stage 1: Build static files
FROM node:20-slim AS build

WORKDIR /app
COPY frontend/package.json ./
COPY frontend/package-lock.json ./
RUN npm ci

COPY frontend/ .
# ...previous steps
ARG VITE_API_URL
ENV VITE_API_URL=$VITE_API_URL


RUN npm run build

