services:
  backend:
    build:
      context: .
      dockerfile: core/Dockerfile
    volumes:
      - ./core:/app/core
      - ./pyproject.toml:/app/pyproject.toml
    environment:
      DJANGO_SECRET_KEY: "testexample"
      DJANGO_DEBUG: "True"
      DJANGO_ALLOWED_HOSTS: "localhost,127.0.0.1,backend"
      USER_AGENT: "laser-slicer/1.0 (boris.legradic@gmail.com)"
    ports:
      - "8000:8000"
    depends_on:
      - frontend

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    environment:
      - VITE_API_URL=http://localhost:8000
    ports:
      - "5173:5173"
    command: npm run dev -- --host