# Generated by Django 5.2.1 on 2025-05-26 07:59

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ContourJob",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("status", models.CharField(default="PENDING", max_length=20)),
                ("progress", models.PositiveSmallIntegerField(default=0)),
                ("params", models.JSONField(blank=True, default=dict)),
                (
                    "result_file",
                    models.FileField(blank=True, null=True, upload_to="job_results/"),
                ),
                ("log", models.TextField(blank=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ElevationJob",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("status", models.CharField(default="PENDING", max_length=20)),
                ("progress", models.PositiveSmallIntegerField(default=0)),
                ("params", models.JSONField(blank=True, default=dict)),
                (
                    "result_file",
                    models.FileField(blank=True, null=True, upload_to="job_results/"),
                ),
                ("log", models.TextField(blank=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="SVGJob",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("status", models.CharField(default="PENDING", max_length=20)),
                ("progress", models.PositiveSmallIntegerField(default=0)),
                ("params", models.JSONField(blank=True, default=dict)),
                (
                    "result_file",
                    models.FileField(blank=True, null=True, upload_to="job_results/"),
                ),
                ("log", models.TextField(blank=True)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
